version: '3.9'
services:
    php:
      build:
        context: .
        dockerfile: ./Dockerfile
      restart: unless-stopped
      container_name: antbot-php
      depends_on:
        mysql:
          condition: service_healthy
        redis:
          condition: service_healthy
      healthcheck:
          test: "php-fpm-healthcheck || exit 1"
          interval: 5s
          retries: 5
          timeout: 60s
    mysql:
      image: mysql:latest
      container_name: antbot-mysql
      restart: unless-stopped
      environment:
        MYSQL_HOST: ${DB_HOST}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      volumes:
        - ${PWD}/docker/mysql:/docker-entrypoint-initdb.d
        - ${PWD}/docker/mysql-volume:/var/lib/mysql:rw
      ports:
      - "${DB_PORT}:3306"
      healthcheck:
        test: "mysql -w --connect-timeout 5 --user=${DB_USERNAME} --password=${DB_PASSWORD} -e 'show databases;'"
        interval: 5s
        retries: 10
        timeout: 60s
    redis:
      image: redis:latest
      container_name: antbot-redis
      command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
      volumes:
      - ${PWD}/docker/redis-volume:/data
      ports:
        - "${REDIS_PORT}:6379"
      healthcheck:
        test: "redis-cli -a ${REDIS_PASSWORD} --raw redis_healthcheck ping"
        interval: 5s
        retries: 10
        timeout: 60s
    nginx:
      image: nginx:stable
      container_name: antbot-nginx
      restart: unless-stopped
      ports:
        - "8080:80"
      volumes:
        - ${PWD}/:/var/www/html
        - ${PWD}/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ${PWD}/storage:/var/www/html/storage
      depends_on:
        php:
          condition: service_healthy