version: '3'
services:
    nginx:
      image: nginx:stable-alpine
      container_name: nginx
      ports:
        - "8080:80"
      volumes:
        - ./:/var/www/html
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./storage:/var/www/html/storage
      depends_on:
        - php
    php:
        build:
          context: .
          dockerfile: ./Dockerfile
        restart: always
        container_name: php

